### PR TITLE
Fix tests for GF(2) algebra

### PR DESCRIPTION
**Pull request by CrafterKolyan**
1. PEP8 coding style
2. After applying `sum` axis should be removed so correct shapes of arrays are `(2, )` and `(3, )` rather than `(1, 2)` and `(1, 3)`
3. Euclid test: no insignificant zeros in result and correct value of `max_deg` (as the answer is `24x^2 + 8x + 11` maximum degree is 2)

Better use these tests:
https://github.com/nikitabobko/applied-algebra-tests

### CODE REVIEW

**Comment by nikitabobko** [comment]
How is it going? Will it be merged?

**Comment by CrafterKolyan** [comment]
@arti32lehtonen Do we want to abandon this pull request or do we want to fix errors that are copied from one repository to another and absolutely ALL students see these errors and need to fix them by themselves?
This commit is not big. You would spent no more than 10 minutes reviewing it.

**Comment by nikitabobko** [comment]
:trollface:

**Comment by arti32lehtonen** [comment]
@CrafterKolyan, thank you

**Pull request merged**
